### ISSUE TITLE
Proposal for feature

### ISSUE THREAD

**Issue by stephancb** [quinnj/SQLite.jl#72] opened 2015-10-05 11:03 UTC
I have written an own Julia module for interfacing to Sqlite, which I don't plan to publish. It is hardly documented, and I wouldn't have the time to support it (I'm happy to send the code to anyone who is interested). My module is used in projects where the queries potentially return very large amounts of data, and from this experience I would like to propose extensions for this package, by which one can avoid allocating huge amounts of memory, provided that the results of queries can be further processed row by row:

1) Have something like query(db::SQLiteDB, sql::String, values=[], rowcb, handthrough). "rowcb" (row callback) is a user supplied Julia function, that is called for each row returned by the query, i.e. until sqlite3_step returns SQLITE_DONE. In my implementation the call is rowcb(handthrough, r::Any[]), where r is a vector containing a row, column by column, and handthrough is any data, that need to be handed to the callback function. When used with these arguments the query function does not return anything.

2) Same idea, but perhaps more elegantly: provide a

query_iterator(db::SQLiteDB, sql::String, values=[]) as well as start,next,done methods. Then one can code, for example:

for irow in query_iterator(db, "select * from mytable;")
     do_something(irow)
end

Best regards,
Stephan (scb@irfu.se)

**Comment by Sean1708** [comment] 2015-10-07 10:28
Dupe of #71, closing.

**Closed by Sean1708** 2015-10-07 10:28 UTC
